import re
import logging
import telegram # Add this import
from typing import List, Dict, Any
from markdown_it import MarkdownIt

logger = logging.getLogger(__name__)

md = MarkdownIt("commonmark", {"breaks": True, "html": False}).enable('table')

def fix_collapsed_tables(text: str) -> str:
    """
    Attempts to restore carriage returns (\n) to Markdown tables generated by LLMs 
    that string arrays together on a single line (e.g. GLM-5).
    """
    if not text or '|' not in text:
        return text
    
    # 1. Standardize spaces between columns collapsing back into newlines
    text = re.sub(r'\|\s+\|', '|\n|', text)
    
    # 2. Split paragraphs that collide with the end of a table
    text = re.sub(r'\|\s+(?=-{2,})', '|\n\n', text) 
    text = re.sub(r'\|\s+(?=#{1,6}\s)', '|\n\n', text)
    
    # 3. Split paragraphs that collide with the start of a new table header
    # Looks for a word character ending with a space, immediately followed by | and a capital letter or format string
    text = re.sub(r'([a-zA-Z0-9\)])\s+(?=\|\s*[\*\_\-]?[A-Za-z])', r'\1\n\n', text)
    
    return text

def sanitize_text_characters(text: str) -> str:
    """
    Replaces various Unicode characters with their standard ASCII equivalents.
    This should only be applied to plain text, not code blocks.
    """
    if not isinstance(text, str):
        return text
    
    replacements = {
        '‑': '-',  # Non-breaking hyphen to standard hyphen
        '•': '- ',
        ' ': ' ',  # Narrow no-break space to standard space
        '“': '"',  # Smart quote to standard quote
        '”': '"',  # Smart quote to standard quote
        '‘': "'",  # Smart quote to standard quote
        '’': "'",  # Smart quote to standard quote
    }
    for unicode_char, ascii_char in replacements.items():
        text = text.replace(unicode_char, ascii_char)
        
    return text

def format_thinking_content(text: str) -> str:
    """
    detects <think>...</think> blocks and formats them as a quoted block.
    """
    if not isinstance(text, str):
        return text
    
    # Check for <think> tags
    pattern = r"<think>(.*?)</think>"
    match = re.search(pattern, text, re.DOTALL)
    if match:
        thought_content = match.group(1).strip()
        # Format as a blockquote with a header
        formatted_thought = f"> **Thought Process**\n> {thought_content.replace(chr(10), chr(10) + '> ')}\n\n"
        
        # Replace the original tag with the formatted version
        text = text.replace(match.group(0), formatted_thought)
        
    return text

class TelegramV2Renderer:
    def __init__(self):
        self.buffer = []  # Use a list for O(1) appends
        self.list_level = 0
        self.link_href = None
        self.ordered_list_stack = [] # To keep track of item numbers for nested ordered lists
        self.is_ordered_list = False # Flag to indicate if current list is ordered
        self.in_blockquote = False # Flag for blockquote context
        
        # Table state
        self.in_table = False
        self.table_rows = []
        self.current_row = []
        self.in_table_cell = False
        self.current_cell_content = []

    def _append_inline(self, text: str):
        if self.in_table_cell:
            self.current_cell_content.append(text)
        else:
            self.buffer.append(text)

    def render(self, tokens: List[Dict[str, Any]]) -> str:
        for i, token in enumerate(tokens):
            handler_name = f"render_{token.type}"
            handler = getattr(self, handler_name, self.render_default)
            handler(token, tokens, i)
        return "".join(self.buffer).strip()

    def render_default(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        if token.children:
            for child in token.children:
                handler_name = f"render_{child.type}"
                handler = getattr(self, handler_name, self.render_default)
                handler(child, token.children, -1)

    def render_text(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        if self.in_table_cell:
            self._append_inline(token.content)
            return
            
        sanitized_content = sanitize_text_characters(token.content)
        escaped_text = telegram.helpers.escape_markdown(sanitized_content, version=2)
        if self.in_blockquote:
            # If inside blockquote, ensure newlines are prefixed with \>
            # But wait, render_text usually doesn't contain newlines unless it's a code block or we missed a split?
            # Actually, softbreaks are separate tokens.
            # If the text itself has newlines (unlikely for 'text' token in commonmark unless preserved?), we handle it.
            pass
        self._append_inline(escaped_text)

    def render_paragraph_open(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int): pass
    def render_paragraph_close(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        # Only add double newline if it's not the last paragraph in the block
        if self.list_level == 0 and index < len(tokens) - 1:
            # Check if next token is blockquote_close
            next_token = tokens[index + 1]
            if next_token.type == 'blockquote_close':
                return
            
            self.buffer.append('\n\n')
            if self.in_blockquote:
                self.buffer.append('\\> ')

    def render_heading_open(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int): self.buffer.append('\n*')
    def render_heading_close(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int): self.buffer.append('*\n')

    def render_bullet_list_open(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        self.list_level += 1
        self.is_ordered_list = False # Set flag for unordered list
    def render_bullet_list_close(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        self.list_level -= 1
        if self.list_level == 0: self.buffer.append('\n')

    def render_ordered_list_open(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        self.list_level += 1
        start = int(token.attrs.get('start', 1)) if token.attrs else 1
        self.ordered_list_stack.append(start)
        self.is_ordered_list = True # Set flag for ordered list
    def render_ordered_list_close(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        self.list_level -= 1
        if self.ordered_list_stack:
            self.ordered_list_stack.pop()
        if self.list_level == 0: self.buffer.append('\n')

    def render_list_item_open(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        # Check if this is a continuation item (hidden)
        if getattr(token, 'hidden', False):
            return

        if self.is_ordered_list and self.ordered_list_stack: # Check flag and stack
            current_number = self.ordered_list_stack[-1]
            self.buffer.append(f'{current_number}\\. ') # Number and escaped dot for ordered lists (preserves numbering across splits)
            self.ordered_list_stack[-1] += 1 # Increment for next item in this ordered list
        else:
            self.buffer.append('\\- ') # Escaped hyphen for unordered list (safer than native bullet which can cause 'reserved character' errors)
    def render_list_item_close(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int): self.buffer.append('\n')

    def render_softbreak(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        self.buffer.append('\n')
        if self.in_blockquote:
            self.buffer.append('\\> ')

    def render_hardbreak(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        self.buffer.append('\n')
        if self.in_blockquote:
            self.buffer.append('\\> ')

    def render_inline(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int): self.render_default(token, tokens, index)

    def render_strong_open(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int): self._append_inline('*')
    def render_strong_close(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int): self._append_inline('*')

    def render_em_open(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int): self._append_inline('_')
    def render_em_close(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int): self._append_inline('_')

    def render_code_inline(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        content = token.content
        if self.in_table_cell:
            self._append_inline(f'`{content}`')
        else:
            self._append_inline(f'`{telegram.helpers.escape_markdown(content, version=2)}`')

    def render_fence(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        lang = token.info.split()[0] if token.info else ''
        content = token.content.rstrip()
        self.buffer.append(f'```{lang}\n{content}\n```\n')
        
    def render_code_block(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        # Indented code block -> Fenced code block
        content = token.content.rstrip()
        self.buffer.append(f'```{content}\n```\n')

    def render_blockquote_open(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        self.buffer.append('\\> ')
        self.in_blockquote = True
    def render_blockquote_close(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        self.buffer.append('\n')
        self.in_blockquote = False
    
    def render_hr(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        self.buffer.append('\n\\-\\-\\-\n')

    def render_image(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        # Render image as a link: [Alt Text](URL)
        alt = token.content or "Image"
        src = token.attrs.get('src', '')
        if self.in_table_cell:
            self._append_inline(f'[{alt}]({src})')
        else:
            self._append_inline(f'[{telegram.helpers.escape_markdown(alt, version=2)}]({telegram.helpers.escape_markdown(src, version=2)})')

    def render_link_open(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        self._append_inline('[')
        self.link_href = token.attrs.get('href', '')
    def render_link_close(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        href = self.link_href or ''
        if self.in_table_cell:
            self._append_inline(f']({href})')
        else:
            self._append_inline(f']({telegram.helpers.escape_markdown(href, version=2)})')
        self.link_href = None

    # --- Table Handlers ---
    def render_table_open(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        self.in_table = True
        self.table_rows = []
        
    def render_table_close(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        self.in_table = False
        if not self.table_rows:
            return
            
        # 1. Determine max width of each column
        # Ensure all rows have same length safely
        max_cols = max(len(row) for row in self.table_rows) if self.table_rows else 0
        col_widths = [0] * max_cols
        
        for row in self.table_rows:
            for i, cell in enumerate(row):
                # Clean up any MarkdownV2 escapes applied by render_text since we're putting this in a code block
                clean_cell = cell.replace('\\', '')
                row[i] = clean_cell
                # Calculate display width (simplified: using string length)
                col_widths[i] = max(col_widths[i], len(clean_cell))
                
        # 2. Format the table using monospace code block for alignment
        formatted_lines = []
        for r_idx, row in enumerate(self.table_rows):
            formatted_row = []
            for c_idx in range(max_cols):
                # Get cell or empty string if row is short
                cell = row[c_idx] if c_idx < len(row) else ""
                # Pad to col_width
                formatted_row.append(cell.ljust(col_widths[c_idx]))
            
            # Join cells with pipe
            formatted_lines.append("| " + " | ".join(formatted_row) + " |")
            
            # Add separator after header row (assuming first row is header)
            if r_idx == 0:
                sep_row = []
                for w in col_widths:
                    sep_row.append("-" * w)
                formatted_lines.append("|-" + "-|-".join(sep_row) + "-|")

        # 3. Add to main buffer as a Telegram code block
        table_text = "\n".join(formatted_lines)
        self.buffer.append(f'\n```\n{table_text}\n```\n')

    def render_thead_open(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int): pass
    def render_thead_close(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int): pass

    def render_tbody_open(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int): pass
    def render_tbody_close(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int): pass

    def render_tr_open(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        self.current_row = []
        
    def render_tr_close(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        self.table_rows.append(self.current_row)
        self.current_row = []

    def render_th_open(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        self.in_table_cell = True
        self.current_cell_content = []
        
    def render_th_close(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        self.current_row.append("".join(self.current_cell_content))
        self.in_table_cell = False

    def render_td_open(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        self.in_table_cell = True
        self.current_cell_content = []
        
    def render_td_close(self, token: Dict[str, Any], tokens: List[Dict[str, Any]], index: int):
        self.current_row.append("".join(self.current_cell_content))
        self.in_table_cell = False

def format_for_telegram_v2(markdown_text: str) -> str:
    # 1. Format thinking blocks (DeepSeek R1 style)
    markdown_text = format_thinking_content(markdown_text)
    
    # 2. Parse Markdown
    tokens = md.parse(markdown_text)
    return TelegramV2Renderer().render(tokens)

def parse_markdown_to_ast(markdown_text: str) -> List[Dict[str, Any]]:
    return md.parse(markdown_text)

def render_ast_to_telegram_v2(tokens: List[Dict[str, Any]]) -> str:
    return TelegramV2Renderer().render(tokens)

def replace_html_tags(text: str) -> str:
    """
    Replaces <br> tags with newlines.
    """
    if not isinstance(text, str):
        return text

    # Replace <br> tags with newlines
    text = re.sub(r'<br\s*/?>', '\n', text, flags=re.IGNORECASE)
    return text

def split_document_ast_aware(tokens: List, max_len: int = 4096) -> List[List]:
    """
    Splits a token stream into chunks of a maximum length, respecting block boundaries
    and maintaining context (closing/re-opening blocks) across chunks.
    """
    chunks = []
    current_chunk = []
    current_len = 0
    
    # Stack of open tokens to track context
    block_stack = []
    
    # Stack of counters for ordered lists
    ordered_list_counters = [] 

    # Helper to clone a token
    def clone_token(t):
        new_t = type(t)(t.type, t.tag, t.nesting)
        new_t.attrs = t.attrs.copy() if t.attrs else {}
        new_t.map = t.map[:] if t.map else None
        new_t.level = t.level
        new_t.content = t.content
        new_t.info = t.info
        new_t.meta = t.meta.copy() if t.meta else {}
        new_t.block = t.block
        new_t.hidden = getattr(t, 'hidden', False)
        new_t.children = [clone_token(c) for c in t.children] if t.children else None
        return new_t

    # Helper to flush current chunk
    def flush_chunk():
        nonlocal current_chunk, current_len
        if not current_chunk: return

        # Close open blocks
        closing_tokens = []
        for open_token in reversed(block_stack):
            close_type = open_token.type.replace('_open', '_close')
            close_token = type(open_token)(close_type, open_token.tag, -1)
            close_token.level = open_token.level
            closing_tokens.append(close_token)
        
        current_chunk.extend(closing_tokens)
        chunks.append(current_chunk)
        
        # Start new chunk
        current_chunk = []
        current_len = 0
        
        # Re-open blocks
        for open_token in block_stack:
            new_open = clone_token(open_token)
            new_open.children = None # Block tokens don't have children usually
            
            if open_token.type == 'ordered_list_open':
                ol_index = 0
                for t in block_stack:
                    if t == open_token: break
                    if t.type == 'ordered_list_open': ol_index += 1
                if ol_index < len(ordered_list_counters):
                    new_open.attrs['start'] = ordered_list_counters[ol_index]
            
            if open_token.type == 'list_item_open':
                new_open.hidden = True
            
            current_chunk.append(new_open)
            current_len += 5

    i = 0
    while i < len(tokens):
        token = tokens[i]
        i += 1
        
        # Calculate Length
        token_len = len(token.content) if token.content else 0
        token_len += 10 # Overhead
        
        # Check if token fits
        if current_len + token_len > max_len:
            # If current chunk is not empty, flush it first
            if current_chunk:
                flush_chunk()
            
            # Now current_chunk is empty (except re-opened blocks).
            # Check if token fits NOW.
            if current_len + token_len > max_len:
                # Token is HUGE. We must split it.
                remaining_space = max_len - current_len - 20
                
                if token.type == 'inline' and token.children:
                    # Split inline token by children
                    # We create a new inline token and fill it with children until full
                    
                    # We need to process children one by one
                    children_queue = token.children[:]
                    
                    while children_queue:
                        # Create a partial inline token
                        partial_inline = clone_token(token)
                        partial_inline.children = []
                        partial_content_len = 0
                        
                        while children_queue:
                            child = children_queue[0]
                            child_len = len(child.content) if child.content else 0
                            child_len += 5 # Overhead
                            
                            if current_len + partial_content_len + child_len < max_len:
                                # Child fits in current partial inline
                                partial_inline.children.append(child)
                                partial_content_len += child_len
                                children_queue.pop(0)
                            else:
                                # Child does NOT fit.
                                if not partial_inline.children:
                                    # Even a single child is too big!
                                    # We must split the child (if it's text).
                                    if child.type == 'text':
                                        space_for_text = max_len - current_len - 20
                                        if space_for_text > 0:
                                            part1_text = child.content[:space_for_text]
                                            part2_text = child.content[space_for_text:]
                                            
                                            child_part1 = clone_token(child)
                                            child_part1.content = part1_text
                                            
                                            child.content = part2_text # Update child for next pass
                                            
                                            partial_inline.children.append(child_part1)
                                            # Don't pop child from queue, we processed part of it
                                            break 
                                        else:
                                            # No space at all? Flush and retry.
                                            break
                                    else:
                                        # Can't split non-text child easily.
                                        # If partial_inline is empty, we are stuck.
                                        # Force add it and let it overflow? Or flush?
                                        break
                                else:
                                    # Partial inline is full.
                                    break
                        
                        if partial_inline.children:
                            current_chunk.append(partial_inline)
                            flush_chunk()
                        else:
                            # We couldn't add anything.
                            # If we just flushed, and still can't add, we are stuck.
                            # Force add one child to avoid infinite loop?
                            if children_queue:
                                force_child = children_queue.pop(0)
                                partial_inline.children.append(force_child)
                                current_chunk.append(partial_inline)
                                flush_chunk()
                    
                    continue # Done processing this huge inline token

                elif token.type in ['fence', 'code_block']:
                    # Split code block content
                    content = token.content
                    while content:
                        space = max_len - current_len - 20
                        if space <= 0:
                            flush_chunk()
                            space = max_len - current_len - 20
                        
                        part = content[:space]
                        content = content[space:]
                        
                        part_token = clone_token(token)
                        part_token.content = part
                        current_chunk.append(part_token)
                        
                        if content: # If there is more, we must flush
                            flush_chunk()
                    continue

        # Add Token
        current_chunk.append(token)
        current_len += token_len
        
        # Update State
        if token.type.endswith('_open'):
            block_stack.append(token)
            if token.type == 'ordered_list_open':
                start = 1
                if token.attrs and 'start' in token.attrs:
                    try:
                        start = int(token.attrs['start'])
                    except (ValueError, TypeError):
                        pass
                ordered_list_counters.append(start)
            elif token.type == 'list_item_open':
                for t in reversed(block_stack[:-1]):
                    if t.type == 'ordered_list_open':
                        if ordered_list_counters:
                            ordered_list_counters[-1] += 1
                        break
                    if t.type == 'bullet_list_open':
                        break

        elif token.type.endswith('_close'):
            if block_stack:
                popped = block_stack.pop()
                if popped.type == 'ordered_list_open':
                    if ordered_list_counters:
                        ordered_list_counters.pop()

    if current_chunk:
        chunks.append(current_chunk)

    return [c for c in chunks if render_ast_to_telegram_v2(c)]